### ISSUE TITLE
谢谢分享， 几个bug

### ISSUE THREAD

**Issue by wwsh123** [AnoldmanLiSir/Acer-V3-572G-51MR#1]
谢谢分享，
bug1，外接显示器无反应，黑屏，
bug2，小太阳，不存在f14，F15,按fn+左右键无反应
bug3，未找到触控板

**Comment by CodeFishK** [comment]
> 谢谢分享，
> bug1，外接显示器无反应，黑屏，
> bug2，小太阳，不存在f14，F15,按fn+左右键无反应
> bug3，未找到触控板

好的，我会慢慢完善的，首先外接显示因为条件原因，未取测试，然后小太阳是通过FN+F12之后的第二个和第四个按键即可实现亮度调节，触控板有时会失效，一般重启即可，如若未找到可以自行重新添加触控板驱动测试即可！

**Comment by wwsh123** [comment]
谢谢

**Comment by CodeFishK** [comment]
> 谢谢

纠正下亮度调节：Fn+F12 降低亮度，Fn+PauseBreak 增加亮度。
