### ISSUE TITLE
新人请教

### ISSUE THREAD

**Issue by xuxinhang233** [AnoldmanLiSir/Acer-V3-572G-51MR#3]
你好，新人求教：抱歉，您能再详细的说说是怎么使用 ” 安装前 -> 10.14.4安装盘 -> EFI “ 这个文件吗？我之前看的教程需要将SSD格式化为Mac的格式，还要提供镜像文件。您的文件只有几十MB，所以我有点迷茫。能否提供详细一点的说明，或者给一个类似问题的链接，十分感谢！

**Comment by CodeFishK** [comment]
> 你好，新人求教：抱歉，您能再详细的说说是怎么使用 ” 安装前 -> 10.14.4安装盘 -> EFI “ 这个文件吗？我之前看的教程需要将SSD格式化为Mac的格式，还要提供镜像文件。您的文件只有几十MB，所以我有点迷茫。能否提供详细一点的说明，或者给一个类似问题的链接，十分感谢！

首先EFI整个文件夹是黑苹果安装时的CLOVER配置及引导文件，黑苹果的完美程度可以说就是依靠里边的配置文件。如果你不知道如何使用整个EFI文件夹，我只能告诉你是拿来替换原来安装盘里的的EFI文件夹即可，具体你可以移步这个网站，它有提供教程与镜像：https://blog.daliansky.net/macOS-Mojave-10.14.4-18E226-official-version-with-Clover-4903-original-image.html
