### ISSUE TITLE
Wireless networking since Big Sur

### ISSUE THREAD

**Issue by rdziubek** [AnoldmanLiSir/Acer-V3-572G-51MR#6]
Keep in mind that BCM4322HM8L will be hindered in Big Sur even more than in Catalina where it's already lost it's 5 GHz capabilities. This time around, you will also not be able to connect to 802.1X-secured networks anymore; neither you'll be able to use AirPlay, as well as possibly some of Apple Continuity Framework's features.

Haven't tested for any other issues though, beware there might be more.

**Comment by CodeFishK** [comment]
Thank you for your suggestion, the project has been discontinued maintenance, I am already using MacBook now.
